name: Build Resume on Push

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

          #- name: Set up LaTeX environment
          #run: |
          #sudo apt-get update
          #sudo apt-get install -y texlive-full

          # - name: Install simpleicons package
          #   run: |
          #     wget https://github.com/ineshbose/simple-icons-latex/releases/download/13.13.0/simpleicons.zip
          #     sudo unzip simpleicons.zip -d /usr/local/texlive/2021/texmf-dist/tex/latex/simpleicons
          #     #sudo cp simpleicons/simpleicons/tex/simpleicons.sty /usr/share/texlive/texmf-dist/tex/latex/simpleicons/
          #     sudo texhash

      - name: LaTeX build
        uses: dante-ev/latex-action@latest
        with:
          root_file: resume.tex

      - name: Upload a Build artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: resume.pdf
          path: resume.pdf

