# This is a basic workflow to help you get started with Actions

name: Build Resume on Push

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: LaTeX build
          uses: dante-ev/latex-action@2021-A
          with:
            root_file: CV.tex

                - name: Upload a Build Artifact
      - name: Upload a Build artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: resume.pdf
          path: resume.pdf

