name: Build Resume on Push

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: LaTeX build
        uses: dante-ev/latex-action@latest
        with:
          root_file: resume.tex

      - name: Upload a Build artifact
        uses: actions/upload-artifact@latest
        with:
          name: resume.pdf
          path: resume.pdf

