name: Build Resume on Push

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

          #- name: Set up LaTeX environment
          #run: |
          #sudo apt-get update
          #sudo apt-get install -y texlive-full

          #- name: Install simpleicons package
          #run: |
          #wget https://mirrors.ctan.org/macros/latex/contrib/simpleicons.zip
          #unzip simpleicons.zip -d simpleicons
          #sudo cp simpleicons/simpleicons.sty /usr/share/texlive/texmf-dist/tex/latex/simpleicons/
          #sudo texhash

      - name: LaTeX build
        uses: dante-ev/latex-action@2021-A
        with:
          root_file: CV.tex

      - name: Upload a Build artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: resume.pdf
          path: resume.pdf

