name: Check HTML and Comment on PR

on:
  workflow_run:
    workflows: ["Build Resume on Push"]  # Name of your build workflow
    types:
      - completed

permissions:
  contents: write
  pull-requests: write
  actions: read

jobs:
  check-html:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download the generated PDF
        uses: actions/download-artifact@v4
        with:
          name: resume.pdf
          path: resume.pdf
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Start a web server
        run: |
          npm install -g http-server
          nohup http-server -p 8080 &

      - name: Modify HTML to use the generated PDF
        run: |
          sed -i 's|https://resume.mgopee.tech/resume.pdf|resume.pdf|' index.html

      - name: Install dependencies
        run: npm install puppeteer

      - name: Take screenshot
        run: |
          node <<'EOF'
          const puppeteer = require('puppeteer');
          (async () => {
            const browser = await puppeteer.launch();
            const page = await browser.newPage();
            await page.goto('http://localhost:8080/index.html', {waitUntil: 'networkidle2'});
            await page.screenshot({ path: 'screenshot.png', fullPage: true });
            await browser.close();
          })();
          EOF

      - name: Upload screenshot
        uses: actions/upload-artifact@v4
        with:
          name: screenshot
          path: screenshot.png

      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Authenticate GitHub CLI
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh auth login --with-token <<< "${GITHUB_TOKEN}"

      - name: Comment on PR with screenshot
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh pr comment ${{ github.event.pull_requests[0].number }} --body "### HTML Rendering Check\n![Screenshot](./screenshot.png)"

